name: test
channels:
  - conda-forge
  - defaults
dependencies:
  - authlib=0.15.2=py_0
  - brotlipy=0.7.0=py36h9ed2024_1003
  - ca-certificates=2020.12.8=hecd8cb5_0
  - certifi=2020.12.5=py36hecd8cb5_0
  - cffi=1.14.4=py36h2125817_0
  - chardet=3.0.4=py36hecd8cb5_1003
  - click=7.1.2=pyh9f0ad1d_0
  - cryptography=3.3.1=py36hbcfaee0_0
  - flask=1.1.2=py_0
  - flask-wtf=0.14.3=py_0
  - icu=67.1=hb1e8313_0
  - idna=2.10=py_0
  - itsdangerous=1.1.0=py36_0
  - jansson=2.13.1=hc929b4f_0
  - jinja2=2.11.2=py_0
  - libcxx=11.0.0=h4c3b8ed_1
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.3=hb1e8313_2
  - libiconv=1.16=haf1e3a3_0
  - libxml2=2.9.10=h2c6e4a5_2
  - markdown2=2.3.10=py_0
  - markupsafe=1.1.1=py36h1de35cc_0
  - mysql-connector-c=6.1.11=hccea1a4_1
  - mysqlclient=2.0.1=py36hb1e8313_0
  - ncurses=6.2=h0a44026_1
  - openssl=1.1.1i=h9ed2024_0
  - pcre=8.44=hb1e8313_0
  - pip=20.3.3=py36hecd8cb5_0
  - pycparser=2.20=py_2
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pysocks=1.7.1=py36hecd8cb5_0
  - python=3.6.12=h26836e1_2
  - python-dotenv=0.15.0=pyhd8ed1ab_0
  - python_abi=3.6=1_cp36m
  - pyyaml=5.3.1=py36haf1e3a3_1
  - readline=8.0=h1de35cc_0
  - requests=2.24.0=py_0
  - setuptools=51.1.2=py36hecd8cb5_3
  - six=1.15.0=py36hecd8cb5_0
  - sqlalchemy=1.3.20=py36haf1e3a3_0
  - sqlite=3.33.0=hffcf06c_0
  - tk=8.6.10=hb0a8c7a_0
  - urllib3=1.25.11=py_0
  - uwsgi=2.0.19.1=py36h073569c_1
  - werkzeug=1.0.1=py_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - wtforms=2.3.3=py_0
  - xz=5.2.5=h1de35cc_0
  - yaml=0.2.5=haf1e3a3_0
  - zlib=1.2.11=h1de35cc_3
prefix: /opt/anaconda3/envs/test
